### ISSUE TITLE
Update Helm charts with hyrax mount paths

### ISSUE THREAD

**Issue by orangewolf** [notch8/stack_car#31]
If the `--hyrax` flag is passed to stack_car, the following volumeMounts configuration needs to be applied:
- [x] `templates/chart/templates/web-deploy.yaml`
- [x] `templates/chart-sidekiq/sidekiq-deploy.yaml`

The mount paths key needs to use the standard hyrax-webapp dirs. In spec.containers:
```
          volumeMounts:
            - mountPath: /app/samvera/hyrax-webapp/tmp/imports
              name: shared
              subPath: import_path
            - mountPath: /app/samvera/hyrax-webapp/tmp/exports
              name: shared
              subPath: export_path
            - mountPath: /app/samvera/hyrax-webapp/tmp/derivatives
              name: shared
              subPath: derivatives_path
            - mountPath: /app/samvera/hyrax-webapp/tmp/network_files
              name: shared
              subPath: network_files
            - mountPath: /app/samvera/hyrax-webapp/public/uploads
              name: shared
              subPath: uploads
            - mountPath: /app/samvera/hyrax-webapp/public/assets
              name: shared
              subPath: assets
            - mountPath: /app/samvera/hyrax-webapp/public/branding
              name: shared
              subPath: branding
```
